name: nike_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.2.0+1
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.0
  persian_number_utility: ^1.1.3
  shared_preferences: ^2.1.2
  smooth_page_indicator: ^1.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: iranyekan
      fonts:
        - asset: assets/fonts/medium.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700